@startuml

(main) --> (주소정보를 입력한다) : 주소록
(주소정보를 입력한다) --> (main) : 주소록
(main) --> (주소정보를 출력한다) : 주소록
(주소정보를 출력한다) --> (main)
(main) --> (주소정보를 삭제한다) : 주소록
(주소정보를 삭제한다) --> (main) : 주소록
(main) --> (주소정보를 수정한다) : 주소록
(주소정보를 수정한다) --> (main) : 주소록
(main) --> (주소정보를 검색한다) : 주소록
(주소정보를 검색한다) --> (main) : 주소정보

@enduml
